In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
print(a)
mean_a = a.mean(axis=0)
mean_a

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


array([2. , 8.4])

In [ ]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [ ]:
a_centered_sp = a_centered[:,0 ] @ a_centered[:, 1]
a_centered_sp / (5-1)

2.0

In [ ]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

In [ ]:
np.cov(a, rowvar=False)

array([[1. , 2. ],
       [2. , 4.3]])

In [156]:
import pandas as pd

In [157]:
authors = pd.DataFrame({
          'author_id': [1, 2, 3],
          'author_name': ['Тургенев', 'Чехов', 'Островский']
          })
book = pd.DataFrame({
        'author_id': [1, 1, 1, 2, 2, 3, 3],
        'book_title': ['Отцы и дети', 'Рудин', "Дворянское гнездо", "Толстый и тонкий", "Дама с собачкой", "Гроза", "Таланты и поклонники"],
        'price': [450, 300, 350, 500, 450, 370, 290]
       })

In [158]:
authors_price = pd.merge(authors, book, on="author_id", how='outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [159]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [160]:
authors_grp = authors_price.groupby(['author_name'])
authors_stat = authors_grp.agg({'price':'min'})
authors_stat = authors_stat.rename(columns={'price':'min_price'})
authors_stat['max_price'] = authors_grp.agg({'price': 'max'})
authors_stat['mean_price'] = authors_grp.agg({'price': 'mean'})
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

In [161]:
authors_price['cover'] = ["твердая", "мягкая", "мягкая", "твердая", "твердая", "мягкая", "мягкая"]
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [162]:
book_info = pd.pivot_table(authors_price, index='author_name', columns='cover', values='price', aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [163]:
book_info.to_pickle('book_info.pkl')
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950